Repository mikepenz/action-junit-report, pull requests merged in 2022-01, with the labels that each got.

#471 fix empty annotation title
  src/testParser.ts
Labels: fix

#478 Dependency updates 2022.01.07
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies

#490 Enhance title for cases with `include_passed` enabled
  .github/workflows/build.yml
  dist/index.js
  dist/index.js.map
  src/main.ts
Labels: feature

#491 Upgrade npm dependencies to latest stable version
  README.md
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies

#493 JUnit retries are handled as passes
  README.md
  __tests__/testParser.test.ts
  dist/index.js
  dist/index.js.map
  src/main.ts
  src/testParser.ts
  test_results/junit-web-test/expectedRetries.xml
Labels: feature
