Repository mikepenz/action-junit-report, pull requests merged in 2022-07, with the labels that each got.

#592 docs: typo
  README.md
Labels: other

#597 Include passed count always in the summary
  dist/index.js
  dist/index.js.map
  src/main.ts
  src/testParser.ts
Labels: feature

#598 Additional action output
  README.md
  dist/index.js
  dist/index.js.map
  src/main.ts
Labels: feature

#599 Dependency updates 2022.07.15
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies

#605 Update dependencies 2022.07.22
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies

#606 Multi-report refactor
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .prettierrc.json
  __tests__/testParser.test.ts
  dist/index.js
  dist/index.js.map
  src/annotator.ts
  src/main.ts
  src/testParser.ts
  src/utils.ts
Labels: other

#613 Dependency updates | webpack 5.74.0
  package-lock.json
  package.json
Labels: dependencies
