Repository mikepenz/action-junit-report, pull requests merged in 2023-05, with the labels that each got.

#843 Update annotator.ts
  src/annotator.ts
Labels: other

#856 Dependency updates
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: dependencies

#864 Offer configuration `require_passed_tests`
  README.md
  action.yml
  dist/index.js
  dist/index.js.map
  src/main.ts
Labels: feature

#868 Common reports paths section in README
  README.md
Labels: other
