Repository mikepenz/action-junit-report, pull requests merged in 2024-11, with the labels that each got.

#1220 Upgrade dependencies to latest major version
  .eslintrc.json
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/sourcemap-register.js
  package-lock.json
  package.json
  src/testParser.ts
  src/utils.ts
Labels: feature

#1221 Add new API to skip annotations all-to-gether
  action.yml
  dist/index.js
  dist/index.js.map
  src/main.ts
Labels: feature

#1222 Introduce flag to `fail_on_parse_error`
  __tests__/utils.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  src/main.ts
  src/testParser.ts
Labels: feature

#1223 Slight code cleanup
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/annotator.ts
Labels: other

#1225 Configuration to enable grouping by TestSuite in the Detail Summary
  .github/workflows/build.yml
  README.md
  __tests__/table.test.ts
  __tests__/testParser.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  src/annotator.ts
  src/main.ts
  src/table.ts
  src/testParser.ts
  test_results/nested/multi-level.xml
Labels: feature

#1237 Upgrade dev npm dependencies
  package-lock.json
  package.json
Labels: dependencies

#1253 Always limit file resolution by workspace root
  __tests__/table.test.ts
  __tests__/testParser.test.ts
  dist/index.js
  dist/index.js.map
  src/main.ts
  src/testParser.ts
  src/utils.ts
Labels: feature, fix

#1254 Upgrade all dev dependencies | ESLint 9
  .eslintignore
  .eslintrc.json
  __tests__/table.test.ts
  __tests__/testParser.test.ts
  dist/index.js
  dist/index.js.map
  eslint.config.mjs
  package-lock.json
  package.json
Labels: dependencies, other

#1238 Add `retried` to output
  __tests__/testParser.test.ts
  dist/index.js
  dist/index.js.map
  src/main.ts
  src/testParser.ts
  test_results/junit-server-test/report.xml
Labels: feature
